spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smarbl_db?useSSL=false&serverTimezone=UTC
    username: root
    password: yourpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  # H2 Configuration (For Testing)
  profiles:
    active: dev  # Switch profiles (dev -> H2, prod -> MySQL)

jwt:
  secret: cxy0iPv+eSznpWTEKraFTRrOuOfQkfRJUNwmcwvmTY8=
  expiration: 86400000
  # 24 hours in milliseconds
##  jwt.secret=6vHdNcR8v2v0Kp/j1M5P3Z+ZkE27hQ==
