package com.smarbl.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import java.util.UUID;

public class PostDTO {

	/***
	 * Represents the primary key for a Post entity. This is usually generated by
	 * the database (@GeneratedValue in JPA).
	 */
	// postId (UUID) → Unique identifier for Post.
	private UUID postId;

	@NotBlank(message = "Post title cannot be empty")
	@Size(min = 3, max = 100, message = "Post title must be between 3 and 100 characters")
	private String postTitle;

	@NotBlank(message = "Post content cannot be empty")
	@Size(min = 10, max = 1000, message = "Post content must be between 10 and 1000 characters")
	private String postContent;

	private String userName; // Simplified, avoid complex user data

	// Default constructor
	public PostDTO() {
	}

	/**
	 * Represents the foreign key linking the Post entity to a User entity. Allows
	 * clients to associate a post with a specific user when creating or retrieving
	 * posts.
	 */
	// userId (UUID) → Foreign key reference to User.
	private UUID userId;

	// Constructor for easy creation
	public PostDTO(UUID postId, String postTitle, String postContent, String userName) {
		this.postId = postId;
		this.postTitle = postTitle;
		this.postContent = postContent;
		this.userName = userName;
	}

	// Ensure this constructor exists explicitly
	public PostDTO(UUID postId, String postTitle, String postContent, UUID userId) {
		this.postId = postId;
		this.postTitle = postTitle;
		this.postContent = postContent;
		this.setUserId(userId);
	}

	// Getters and Setters
	public UUID getPostId() {
		return postId;
	}

	public void setPostId(UUID postId) {
		this.postId = postId;
	}

	public String getPostTitle() {
		return postTitle;
	}

	public void setPostTitle(String postTitle) {
		this.postTitle = postTitle;
	}

	public String getPostContent() {
		return postContent;
	}

	public void setPostContent(String postContent) {
		this.postContent = postContent;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * @return the userId
	 */
	public UUID getUserId() {
		return userId;
	}

	/**
	 * @param userId the userId to set
	 */
	public void setUserId(UUID userId) {
		this.userId = userId;
	}

	@Override
	public String toString() {
		return "PostDTO{" + "postId=" + postId + ", postTitle='" + postTitle + '\'' + ", postContent='" + postContent
				+ '\'' + ", userName='" + userName + '\'' + '}';
	}

}
